version: "3.8"
services: 
  react-app:
    image: certifylite-container
    stdin_open: true
    ports:
      - "3000:3000"
    volumes: 
      - "./:/usr/src/app:delegated"
      - "/usr/src/app/node_modules/"


  